/**
 * Viasoft.Analytics.UserBehaviour
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Groupings = 'App' | 'Domain' | 'Tenant';

export const Groupings = {
    App: 'App' as Groupings,
    Domain: 'Domain' as Groupings,
    Tenant: 'Tenant' as Groupings
};

