/**
 * Viasoft.Analytics.UserBehaviour
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

import { FilterByGroupingOutput } from '../model/filterByGroupingOutput';
import { Groupings } from '../model/groupings';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { UsageSearchFilter } from '../../../app/common/gadgets/usage-search-base-gadget/usage-search-filter';



@Injectable()
export class UsageSearchServiceProxy {

    protected basePath = 'http://localhost';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();
    public encoder: HttpParameterCodec;

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (configuration) {
            this.configuration = configuration;
        }
        if (typeof this.configuration.basePath !== 'string') {
            if (typeof basePath !== 'string') {
                basePath = this.basePath;
            }
            this.configuration.basePath = basePath;
        }
        this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
    }



    /**
     * @param groupings
     * @param advancedFilter
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public filterByGrouping(groupings?: Groupings, advancedFilter?: string, filter?: UsageSearchFilter, observe?: 'body', reportProgress?: boolean): Observable<FilterByGroupingOutput>;
    public filterByGrouping(groupings?: Groupings, advancedFilter?: string, filter?: UsageSearchFilter, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<FilterByGroupingOutput>>;
    public filterByGrouping(groupings?: Groupings, advancedFilter?: string, filter?: UsageSearchFilter, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<FilterByGroupingOutput>>;
    public filterByGrouping(groupings?: Groupings, advancedFilter?: string, filter?: UsageSearchFilter, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (groupings !== undefined && groupings !== null) {
            queryParameters = queryParameters.set('Groupings', <any>groupings);
        }
        if (advancedFilter !== undefined && advancedFilter !== null) {
            queryParameters = queryParameters.set('AdvancedFilter', <any>advancedFilter);
        }
        if (filter !== undefined && filter !== null) {
            queryParameters = queryParameters.set('DateInterval', <any>filter.dateInterval);
            if (filter.maxResultCount) {
              queryParameters = queryParameters.set('MaxResultCount', <any>filter.maxResultCount);
            }
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }
        return this.httpClient.get<FilterByGroupingOutput>(`${this.configuration.basePath}/api/Analytics/UserBehaviour/UsageSearch/FilterByGrouping`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
