/**
 * Viasoft.Analytics.UserBehaviour
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

import { OnlineAppsCountOutput } from '../model/onlineAppsCountOutput';
import { OnlineTenantCountOutput } from '../model/onlineTenantCountOutput';
import { OnlineUserCountOutput } from '../model/onlineUserCountOutput';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';



@Injectable()
export class UserBehaviourAnalyticsServiceProxy {

    protected basePath = 'http://localhost';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();
    public encoder: HttpParameterCodec;

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (configuration) {
            this.configuration = configuration;
        }
        if (typeof this.configuration.basePath !== 'string') {
            if (typeof basePath !== 'string') {
                basePath = this.basePath;
            }
            this.configuration.basePath = basePath;
        }
        this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
    }



    /**
     * @param advancedFilter 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public countAllOnlineApps(advancedFilter?: string, observe?: 'body', reportProgress?: boolean): Observable<OnlineAppsCountOutput>;
    public countAllOnlineApps(advancedFilter?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<OnlineAppsCountOutput>>;
    public countAllOnlineApps(advancedFilter?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<OnlineAppsCountOutput>>;
    public countAllOnlineApps(advancedFilter?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (advancedFilter !== undefined && advancedFilter !== null) {
            queryParameters = queryParameters.set('advancedFilter', <any>advancedFilter);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.get<OnlineAppsCountOutput>(`${this.configuration.basePath}/api/Analytics/UserBehaviour/UserBehaviourAnalytics/CountAllOnlineApps`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public countAllOnlineTenants(observe?: 'body', reportProgress?: boolean): Observable<OnlineTenantCountOutput>;
    public countAllOnlineTenants(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<OnlineTenantCountOutput>>;
    public countAllOnlineTenants(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<OnlineTenantCountOutput>>;
    public countAllOnlineTenants(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.get<OnlineTenantCountOutput>(`${this.configuration.basePath}/api/Analytics/UserBehaviour/UserBehaviourAnalytics/CountAllOnlineTenants`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param advancedFilter 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public countAllOnlineUsers(advancedFilter?: string, observe?: 'body', reportProgress?: boolean): Observable<OnlineUserCountOutput>;
    public countAllOnlineUsers(advancedFilter?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<OnlineUserCountOutput>>;
    public countAllOnlineUsers(advancedFilter?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<OnlineUserCountOutput>>;
    public countAllOnlineUsers(advancedFilter?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (advancedFilter !== undefined && advancedFilter !== null) {
            queryParameters = queryParameters.set('advancedFilter', <any>advancedFilter);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.get<OnlineUserCountOutput>(`${this.configuration.basePath}/api/Analytics/UserBehaviour/UserBehaviourAnalytics/CountAllOnlineUsers`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
