/**
 * Viasoft.Analytics.UserBehaviour
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Domains = 'Sales' | 'Purchases' | 'Billing' | 'Financial' | 'Rma' | 'Logistics' | 'Fiscal' | 'Accounting' | 'Engineering' | 'Production' | 'Maintenance' | 'QualityAssurance' | 'HumanResources' | 'Configurations' | 'Development' | 'Customized' | 'Licensing' | 'Reports' | 'Mobile';

export const Domains = {
    Sales: 'Sales' as Domains,
    Purchases: 'Purchases' as Domains,
    Billing: 'Billing' as Domains,
    Financial: 'Financial' as Domains,
    Rma: 'Rma' as Domains,
    Logistics: 'Logistics' as Domains,
    Fiscal: 'Fiscal' as Domains,
    Accounting: 'Accounting' as Domains,
    Engineering: 'Engineering' as Domains,
    Production: 'Production' as Domains,
    Maintenance: 'Maintenance' as Domains,
    QualityAssurance: 'QualityAssurance' as Domains,
    HumanResources: 'HumanResources' as Domains,
    Configurations: 'Configurations' as Domains,
    Development: 'Development' as Domains,
    Customized: 'Customized' as Domains,
    Licensing: 'Licensing' as Domains,
    Reports: 'Reports' as Domains,
    Mobile: 'Mobile' as Domains
};

