/**
 * Viasoft.Analytics.UserBehaviour
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Domains } from './domains';
import { LicensedAppStatus } from './licensedAppStatus';
import { LicensingStatus } from './licensingStatus';


export interface LicenseUsageHistoryOutput { 
    id?: string;
    licensingIdentifier?: string;
    appIdentifier?: string | null;
    appName?: string | null;
    bundleIdentifier?: string | null;
    bundleName?: string | null;
    softwareName?: string | null;
    softwareIdentifier?: string | null;
    appLicenses?: number;
    appLicensesConsumed?: number;
    additionalLicenses?: number;
    additionalLicensesConsumed?: number;
    additionalLicense?: boolean;
    startTime?: Date;
    endTime?: Date | null;
    user?: string | null;
    cnpj?: string | null;
    lastUpdate?: Date;
    licensingStatus?: LicensingStatus;
    appStatus?: LicensedAppStatus;
    softwareVersion?: string | null;
    hostName?: string | null;
    hostUser?: string | null;
    localIpAddress?: string | null;
    language?: string | null;
    osInfo?: string | null;
    browserInfo?: string | null;
    databaseName?: string | null;
    accessDuration?: string;
    accessDurationInMinutes?: number;
    accountName?: string | null;
    domain?: Domains;
    readonly accessDurationFormatted?: string | null;
}

