// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Viasoft.Analytics.UserBehaviour.Infrastructure.PostgreSql.EntityFrameworkCore;

namespace Viasoft.Analytics.UserBehaviour.Infrastructure.PostgreSql.Migrations
{
    [DbContext(typeof(ViasoftAnalyticsUserBehaviourDbContext))]
    partial class ViasoftAnalyticsUserBehaviourDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Viasoft.Analytics.UserBehaviour.Domain.Entities.LicenseUsageHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accountid");

                    b.Property<string>("AccountName")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("accountname");

                    b.Property<bool>("AdditionalLicense")
                        .HasColumnType("boolean")
                        .HasColumnName("additionallicense");

                    b.Property<int>("AdditionalLicenses")
                        .HasColumnType("integer")
                        .HasColumnName("additionallicenses");

                    b.Property<int>("AdditionalLicensesConsumed")
                        .HasColumnType("integer")
                        .HasColumnName("additionallicensesconsumed");

                    b.Property<string>("AppIdentifier")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("appidentifier");

                    b.Property<int>("AppLicenses")
                        .HasColumnType("integer")
                        .HasColumnName("applicenses");

                    b.Property<int>("AppLicensesConsumed")
                        .HasColumnType("integer")
                        .HasColumnName("applicensesconsumed");

                    b.Property<string>("AppName")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("appname");

                    b.Property<int>("AppStatus")
                        .HasColumnType("integer")
                        .HasColumnName("appstatus");

                    b.Property<string>("BrowserInfo")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("browserinfo");

                    b.Property<string>("BundleIdentifier")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("bundleidentifier");

                    b.Property<string>("BundleName")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("bundlename");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("cnpj");

                    b.Property<string>("DatabaseName")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("databasename");

                    b.Property<int>("Domain")
                        .HasColumnType("integer")
                        .HasColumnName("domain");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("endtime");

                    b.Property<string>("Hash")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("hash");

                    b.Property<string>("HostName")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("hostname");

                    b.Property<string>("HostUser")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("hostuser");

                    b.Property<string>("Language")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("language");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lastupdate");

                    b.Property<Guid>("LicensingIdentifier")
                        .HasColumnType("uuid")
                        .HasColumnName("licensingidentifier");

                    b.Property<int?>("LicensingMode")
                        .HasColumnType("integer")
                        .HasColumnName("licensingmode");

                    b.Property<int>("LicensingModel")
                        .HasColumnType("integer")
                        .HasColumnName("licensingmodel");

                    b.Property<int>("LicensingStatus")
                        .HasColumnType("integer")
                        .HasColumnName("licensingstatus");

                    b.Property<string>("LocalIpAddress")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("localipaddress");

                    b.Property<string>("OsInfo")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("osinfo");

                    b.Property<string>("SoftwareIdentifier")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("softwareidentifier");

                    b.Property<string>("SoftwareName")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("softwarename");

                    b.Property<string>("SoftwareVersion")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("softwareversion");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("starttime");

                    b.Property<string>("User")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("user");

                    b.HasKey("Id")
                        .HasName("pk_licenseusagehistory");

                    b.HasIndex("LicensingIdentifier", "EndTime")
                        .HasDatabaseName("ix_licenseusagehistory_licensingidentifier_endtime");

                    b.HasIndex("LicensingIdentifier", "Hash", "EndTime")
                        .HasDatabaseName("ix_licenseusagehistory_licensingidentifier_hash_endtime");

                    b.HasIndex("LicensingIdentifier", "StartTime", "Hash")
                        .HasDatabaseName("ix_licenseusagehistory_licensingidentifier_starttime_hash");

                    b.ToTable("licenseusagehistory");
                });

            modelBuilder.Entity("Viasoft.Analytics.UserBehaviour.Domain.Entities.LicenseUsageHistoryIndex", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FailureStackTrace")
                        .HasColumnType("text")
                        .HasColumnName("failurestacktrace");

                    b.Property<bool>("HasEsFailedSinceLastReindex")
                        .HasColumnType("boolean")
                        .HasColumnName("hasesfailedsincelastreindex");

                    b.Property<bool>("IsIndexing")
                        .HasColumnType("boolean")
                        .HasColumnName("isindexing");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lastmodificationtime");

                    b.Property<Guid?>("ReindexIdentifier")
                        .HasColumnType("uuid")
                        .HasColumnName("reindexidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.HasKey("Id")
                        .HasName("pk_licenseusagehistoryindex");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_licenseusagehistoryindex_tenantid");

                    b.ToTable("licenseusagehistoryindex");
                });

            modelBuilder.Entity("Viasoft.Analytics.UserBehaviour.Domain.Entities.LicenseUsageReporting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Day")
                        .HasColumnType("integer")
                        .HasColumnName("day");

                    b.Property<DateTime>("EndInterval")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("endinterval");

                    b.Property<Guid>("LicensingIdentifier")
                        .HasColumnType("uuid")
                        .HasColumnName("licensingidentifier");

                    b.Property<DateTime>("StartInterval")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("startinterval");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenantid");

                    b.Property<int>("UsageCount")
                        .HasColumnType("integer")
                        .HasColumnName("usagecount");

                    b.HasKey("Id")
                        .HasName("pk_licenseusagereporting");

                    b.ToTable("licenseusagereporting");
                });
#pragma warning restore 612, 618
        }
    }
}
