export enum Domain {
    'sales' = 0,
    'purchases' = 1,
    'billing' = 2,
    'financial' = 3,
    'rma' = 4,
    'logistics' = 5,
    'fiscal' = 6,
    'accounting' = 7,
    'engineering' = 8,
    'production' = 9,
    'maintenance' = 10,
    'qualityAssurance' = 11,
    'humanResources' = 12,
    'configurations' = 13,
    'development' = 14,
    'customized' = 15,
    'licensing' = 16,
    'reports' = 17,
    'mobile' = 18
}
