// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Viasoft.Analytics.UserBehaviour.Infrastructure.EntityFrameworkCore;

namespace Viasoft.Analytics.UserBehaviour.Infrastructure.Migrations
{
    [DbContext(typeof(ViasoftAnalyticsUserBehaviourDbContext))]
    [Migration("20210914000442_AddingLicensingIdentifierEndTimeIndex")]
    partial class AddingLicensingIdentifierEndTimeIndex
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Viasoft.Analytics.UserBehaviour.Domain.Entities.LicenseUsageHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountName")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("AdditionalLicense")
                        .HasColumnType("bit");

                    b.Property<int>("AdditionalLicenses")
                        .HasColumnType("int");

                    b.Property<int>("AdditionalLicensesConsumed")
                        .HasColumnType("int");

                    b.Property<string>("AppIdentifier")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AppLicenses")
                        .HasColumnType("int");

                    b.Property<int>("AppLicensesConsumed")
                        .HasColumnType("int");

                    b.Property<string>("AppName")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AppStatus")
                        .HasColumnType("int");

                    b.Property<string>("BrowserInfo")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BundleIdentifier")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BundleName")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DatabaseName")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Domain")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Hash")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HostName")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HostUser")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Language")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LicensingIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("LicensingMode")
                        .HasColumnType("int");

                    b.Property<int>("LicensingModel")
                        .HasColumnType("int");

                    b.Property<int>("LicensingStatus")
                        .HasColumnType("int");

                    b.Property<string>("LocalIpAddress")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OsInfo")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SoftwareIdentifier")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SoftwareName")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SoftwareVersion")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("User")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("LicensingIdentifier", "EndTime");

                    b.HasIndex("LicensingIdentifier", "Hash", "EndTime");

                    b.ToTable("LicenseUsageHistory");
                });

            modelBuilder.Entity("Viasoft.Analytics.UserBehaviour.Domain.Entities.LicenseUsageHistoryIndex", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("HasEsFailedSinceLastReindex")
                        .HasColumnType("bit");

                    b.Property<bool>("IsIndexing")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReindexIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReindexTries")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("LicenseUsageHistoryIndex");
                });

            modelBuilder.Entity("Viasoft.Analytics.UserBehaviour.Domain.Entities.LicenseUsageReporting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndInterval")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LicensingIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartInterval")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UsageCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LicenseUsageReporting");
                });
#pragma warning restore 612, 618
        }
    }
}
