DECLARE @TIPO_DRE AS VARCHAR(100)

SET @TIPO_DRE = 'DREBI'
---INSERE DRE PARA BI
IF NOT EXISTS(SELECT * FROM CT_DEMONSTRACAO WHERE TIPO = @TIPO_DRE)
BEGIN
	INSERT INTO CT_DEMONSTRACAO (NOME, TIPO)
	VALUES('DRE Power BI', @TIPO_DRE)
END


---EXCLUI EVENTUAIS CONTAS VINCULADAS A ESSA DRE
DELETE CT_DEMONSTRACAO_LINHA_CONTAS WHERE RECNO_CT_DEMONSTRACAO_LINHA IN(
  SELECT CT_DEMONSTRACAO_LINHA.R_E_C_N_O_ FROM CT_DEMONSTRACAO_LINHA 
  INNER JOIN CT_DEMONSTRACAO  ON CT_DEMONSTRACAO.R_E_C_N_O_ = CT_DEMONSTRACAO_LINHA.RECNO_CT_DEMONSTRACAO
	WHERE CT_DEMONSTRACAO.TIPO = @TIPO_DRE

)

---EXCLUI EVENTUAIS LINHAS CRIADAS NA DRE BI
DELETE CT_DEMONSTRACAO_LINHA WHERE RECNO_CT_DEMONSTRACAO IN(
	SELECT TOP(1) R_E_C_N_O_ FROM CT_DEMONSTRACAO WHERE TIPO = @TIPO_DRE ORDER BY R_E_C_N_O_ DESC
)

---INSERE AS LINHAS DA DRE PADRÃO
INSERT INTO CT_DEMONSTRACAO_LINHA(LINHA, DESCRICAO, ORDEM, COLUNA_1, RECNO_CT_DEMONSTRACAO)
VALUES('1', '(+) RECEITA BRUTA', '1', '+', (SELECT TOP(1) R_E_C_N_O_ FROM CT_DEMONSTRACAO WHERE TIPO = @TIPO_DRE ORDER BY R_E_C_N_O_ DESC))

INSERT INTO CT_DEMONSTRACAO_LINHA(LINHA, DESCRICAO, ORDEM, COLUNA_1, RECNO_CT_DEMONSTRACAO)
VALUES('2', '(-) DEDUÇÕES DA RECEITA', '2', '-', (SELECT TOP(1) R_E_C_N_O_ FROM CT_DEMONSTRACAO WHERE TIPO = @TIPO_DRE ORDER BY R_E_C_N_O_ DESC))

INSERT INTO CT_DEMONSTRACAO_LINHA(LINHA, DESCRICAO, ORDEM, COLUNA_1, RECNO_CT_DEMONSTRACAO)
VALUES('3', '(=) RECEITA LÍQUIDA', '3', '=', (SELECT TOP(1) R_E_C_N_O_ FROM CT_DEMONSTRACAO WHERE TIPO = @TIPO_DRE ORDER BY R_E_C_N_O_ DESC))

INSERT INTO CT_DEMONSTRACAO_LINHA(LINHA, DESCRICAO, ORDEM, COLUNA_1, RECNO_CT_DEMONSTRACAO)
VALUES('4', '(-) CUSTO DOS PRODUTOS VENDIDOS', '4', '-', (SELECT TOP(1) R_E_C_N_O_ FROM CT_DEMONSTRACAO WHERE TIPO = @TIPO_DRE ORDER BY R_E_C_N_O_ DESC))

INSERT INTO CT_DEMONSTRACAO_LINHA(LINHA, DESCRICAO, ORDEM, COLUNA_1, RECNO_CT_DEMONSTRACAO)
VALUES('5', '(-) DESPESAS VARIÁVEIS', '5', '-', (SELECT TOP(1) R_E_C_N_O_ FROM CT_DEMONSTRACAO WHERE TIPO = @TIPO_DRE ORDER BY R_E_C_N_O_ DESC))

INSERT INTO CT_DEMONSTRACAO_LINHA(LINHA, DESCRICAO, ORDEM, COLUNA_1, RECNO_CT_DEMONSTRACAO)
VALUES('6', '(=) LUCRO BRUTO E MARGEM DE CONTRIBUIÇÃO', '6', '=', (SELECT TOP(1) R_E_C_N_O_ FROM CT_DEMONSTRACAO WHERE TIPO = @TIPO_DRE ORDER BY R_E_C_N_O_ DESC))

INSERT INTO CT_DEMONSTRACAO_LINHA(LINHA, DESCRICAO, ORDEM, COLUNA_1, RECNO_CT_DEMONSTRACAO)
VALUES('7', '(-) DESPESAS GERAIS E ADMINISTRATIVAS', '7', '-', (SELECT TOP(1) R_E_C_N_O_ FROM CT_DEMONSTRACAO WHERE TIPO = @TIPO_DRE ORDER BY R_E_C_N_O_ DESC))

INSERT INTO CT_DEMONSTRACAO_LINHA(LINHA, DESCRICAO, ORDEM, COLUNA_1, RECNO_CT_DEMONSTRACAO)
VALUES('8', '(-) DESPESAS COMERCIAIS', '8', '-', (SELECT TOP(1) R_E_C_N_O_ FROM CT_DEMONSTRACAO WHERE TIPO = @TIPO_DRE ORDER BY R_E_C_N_O_ DESC))

INSERT INTO CT_DEMONSTRACAO_LINHA(LINHA, DESCRICAO, ORDEM, COLUNA_1, RECNO_CT_DEMONSTRACAO)
VALUES('9', '(-) OUTRAS DESPESAS OPERACIONAIS', '9', '-', (SELECT TOP(1) R_E_C_N_O_ FROM CT_DEMONSTRACAO WHERE TIPO = @TIPO_DRE ORDER BY R_E_C_N_O_ DESC))

INSERT INTO CT_DEMONSTRACAO_LINHA(LINHA, DESCRICAO, ORDEM, COLUNA_1, RECNO_CT_DEMONSTRACAO)
VALUES('10', '(+) OUTRAS RECEITAS OPERACIONAIS', '10', '+', (SELECT TOP(1) R_E_C_N_O_ FROM CT_DEMONSTRACAO WHERE TIPO = @TIPO_DRE ORDER BY R_E_C_N_O_ DESC))

INSERT INTO CT_DEMONSTRACAO_LINHA(LINHA, DESCRICAO, ORDEM, COLUNA_1, RECNO_CT_DEMONSTRACAO)
VALUES('11', '(=) EBITDA', '11', '=', (SELECT TOP(1) R_E_C_N_O_ FROM CT_DEMONSTRACAO WHERE TIPO = @TIPO_DRE ORDER BY R_E_C_N_O_ DESC))

INSERT INTO CT_DEMONSTRACAO_LINHA(LINHA, DESCRICAO, ORDEM, COLUNA_1, RECNO_CT_DEMONSTRACAO)
VALUES('12', '(-) DEPRECIAÇÕES E AMORTIZAÇÕES', '12', '-', (SELECT TOP(1) R_E_C_N_O_ FROM CT_DEMONSTRACAO WHERE TIPO = @TIPO_DRE ORDER BY R_E_C_N_O_ DESC))

INSERT INTO CT_DEMONSTRACAO_LINHA(LINHA, DESCRICAO, ORDEM, COLUNA_1, RECNO_CT_DEMONSTRACAO)
VALUES('13', '(=) LUCRO OPERACIONAL', '13', '=', (SELECT TOP(1) R_E_C_N_O_ FROM CT_DEMONSTRACAO WHERE TIPO = @TIPO_DRE ORDER BY R_E_C_N_O_ DESC))

INSERT INTO CT_DEMONSTRACAO_LINHA(LINHA, DESCRICAO, ORDEM, COLUNA_1, RECNO_CT_DEMONSTRACAO)
VALUES('14', '(+) RECEITAS FINANCEIRAS', '14', '+', (SELECT TOP(1) R_E_C_N_O_ FROM CT_DEMONSTRACAO WHERE TIPO = @TIPO_DRE ORDER BY R_E_C_N_O_ DESC))

INSERT INTO CT_DEMONSTRACAO_LINHA(LINHA, DESCRICAO, ORDEM, COLUNA_1, RECNO_CT_DEMONSTRACAO)
VALUES('15', '(-) DESPESAS FINANCEIRAS', '15', '-', (SELECT TOP(1) R_E_C_N_O_ FROM CT_DEMONSTRACAO WHERE TIPO = @TIPO_DRE ORDER BY R_E_C_N_O_ DESC))

INSERT INTO CT_DEMONSTRACAO_LINHA(LINHA, DESCRICAO, ORDEM, COLUNA_1, RECNO_CT_DEMONSTRACAO)
VALUES('16', '(=) LUCRO ANTES DO IR', '16', '=', (SELECT TOP(1) R_E_C_N_O_ FROM CT_DEMONSTRACAO WHERE TIPO = @TIPO_DRE ORDER BY R_E_C_N_O_ DESC))

INSERT INTO CT_DEMONSTRACAO_LINHA(LINHA, DESCRICAO, ORDEM, COLUNA_1, RECNO_CT_DEMONSTRACAO)
VALUES('17', '(-) PROVISÃO DE IMPOSTOS', '17', '-', (SELECT TOP(1) R_E_C_N_O_ FROM CT_DEMONSTRACAO WHERE TIPO = @TIPO_DRE ORDER BY R_E_C_N_O_ DESC))

INSERT INTO CT_DEMONSTRACAO_LINHA(LINHA, DESCRICAO, ORDEM, COLUNA_1, RECNO_CT_DEMONSTRACAO)
VALUES('18', '(=) LUCRO LÍQUIDO', '18', '=', (SELECT TOP(1) R_E_C_N_O_ FROM CT_DEMONSTRACAO WHERE TIPO = @TIPO_DRE ORDER BY R_E_C_N_O_ DESC))



---INSERE AS CONTAS PARTICIPANTES

---RECEITA BRUTA
INSERT INTO CT_DEMONSTRACAO_LINHA_CONTAS( RECNO_CT_DEMONSTRACAO_LINHA, CODIGO_CT_PLANO_CONTAS)
SELECT (SELECT R_E_C_N_O_ FROM CT_DEMONSTRACAO_LINHA WHERE DESCRICAO = '(+) RECEITA BRUTA'),
CT_PLANO_CONTAS.CODIGO
FROM CT_PLANO_CONTAS
LEFT JOIN CT_PLANO_REFERENCIAL ON CT_PLANO_REFERENCIAL.COD_CTA_REF = CT_PLANO_CONTAS.COD_CTA_REF
WHERE REPLACE(CT_PLANO_CONTAS.COD_CTA_REF, '.', '') >= '301010101'
AND REPLACE(CT_PLANO_CONTAS.COD_CTA_REF, '.', '') < '301010102'
AND CT_PLANO_CONTAS.SINTETICO = 'N'


---DEDUÇÕES DA RECEITA
INSERT INTO CT_DEMONSTRACAO_LINHA_CONTAS( RECNO_CT_DEMONSTRACAO_LINHA, CODIGO_CT_PLANO_CONTAS)
SELECT (SELECT R_E_C_N_O_ FROM CT_DEMONSTRACAO_LINHA WHERE DESCRICAO = '(-) DEDUÇÕES DA RECEITA'),
CT_PLANO_CONTAS.CODIGO
FROM CT_PLANO_CONTAS
LEFT JOIN CT_PLANO_REFERENCIAL ON CT_PLANO_REFERENCIAL.COD_CTA_REF = CT_PLANO_CONTAS.COD_CTA_REF
WHERE REPLACE(CT_PLANO_CONTAS.COD_CTA_REF, '.', '') >= '301010102'
AND REPLACE(CT_PLANO_CONTAS.COD_CTA_REF, '.', '') < '301010103'
AND CT_PLANO_CONTAS.SINTETICO = 'N'


---(-) CUSTO DOS PRODUTOS VENDIDOS
INSERT INTO CT_DEMONSTRACAO_LINHA_CONTAS( RECNO_CT_DEMONSTRACAO_LINHA, CODIGO_CT_PLANO_CONTAS)
SELECT (SELECT R_E_C_N_O_ FROM CT_DEMONSTRACAO_LINHA WHERE DESCRICAO = '(-) CUSTO DOS PRODUTOS VENDIDOS'),
CT_PLANO_CONTAS.CODIGO
FROM CT_PLANO_CONTAS
LEFT JOIN CT_PLANO_REFERENCIAL ON CT_PLANO_REFERENCIAL.COD_CTA_REF = CT_PLANO_CONTAS.COD_CTA_REF
WHERE REPLACE(CT_PLANO_CONTAS.COD_CTA_REF, '.', '') >= '3010103'
AND REPLACE(CT_PLANO_CONTAS.COD_CTA_REF, '.', '') < '3010104'
AND CT_PLANO_CONTAS.SINTETICO = 'N'


---DESPESAS VARIÁVEIS
INSERT INTO CT_DEMONSTRACAO_LINHA_CONTAS( RECNO_CT_DEMONSTRACAO_LINHA, CODIGO_CT_PLANO_CONTAS)
SELECT (SELECT R_E_C_N_O_ FROM CT_DEMONSTRACAO_LINHA WHERE DESCRICAO = '(-) DESPESAS VARIÁVEIS'),
CT_PLANO_CONTAS.CODIGO
FROM CT_PLANO_CONTAS 
LEFT JOIN CT_PLANO_REFERENCIAL ON CT_PLANO_REFERENCIAL.COD_CTA_REF = CT_PLANO_CONTAS.COD_CTA_REF
WHERE CT_PLANO_CONTAS.SINTETICO = 'N' 
AND REPLACE(CT_PLANO_CONTAS.COD_CTA_REF, '.', '') >= '3010107'
AND REPLACE(CT_PLANO_CONTAS.COD_CTA_REF, '.', '') < '3010110'
AND REPLACE(CT_PLANO_CONTAS.COD_CTA_REF, '.', '') NOT IN('30101070124', '30101070123') ---DEPRECIAÇÃO, AMORTIZAÇÃO
AND (NOME LIKE '%COMISSÃO%' OR NOME LIKE '%COMISSAO%'  OR NOME LIKE '%FRETE S/ VENDA%' OR NOME LIKE '%FRETES S/ VENDA%')





---(-) DESPESAS ADMINISTRATIVAS
INSERT INTO CT_DEMONSTRACAO_LINHA_CONTAS( RECNO_CT_DEMONSTRACAO_LINHA, CODIGO_CT_PLANO_CONTAS)
SELECT (SELECT R_E_C_N_O_ FROM CT_DEMONSTRACAO_LINHA WHERE DESCRICAO = '(-) DESPESAS GERAIS E ADMINISTRATIVAS'),
CT_PLANO_CONTAS.CODIGO
FROM CT_PLANO_CONTAS
LEFT JOIN CT_PLANO_REFERENCIAL ON CT_PLANO_REFERENCIAL.COD_CTA_REF = CT_PLANO_CONTAS.COD_CTA_REF
WHERE CT_PLANO_CONTAS.SINTETICO = 'N' 
AND REPLACE(CT_PLANO_CONTAS.COD_CTA_REF, '.', '') >= '3010107'
AND REPLACE(CT_PLANO_CONTAS.COD_CTA_REF, '.', '') < '3010108'
AND REPLACE(CT_PLANO_CONTAS.COD_CTA_REF, '.', '') NOT IN('30101070124', '30101070123') ---DEPRECIAÇÃO, AMORTIZAÇÃO
AND (NOME NOT LIKE '%COMERCIAL%' AND  NOME NOT LIKE '%VENDAS%' AND NOME not LIKE '%COMISSÃO%' and NOME not LIKE '%COMISSAO%' and NOME not LIKE '%FRETE S/ VENDA%' and NOME not LIKE '%FRETES S/ VENDA%')



---DESPESAS COMERCIAIS
INSERT INTO CT_DEMONSTRACAO_LINHA_CONTAS( RECNO_CT_DEMONSTRACAO_LINHA, CODIGO_CT_PLANO_CONTAS)
SELECT (SELECT R_E_C_N_O_ FROM CT_DEMONSTRACAO_LINHA WHERE DESCRICAO = '(-) DESPESAS COMERCIAIS'),
CT_PLANO_CONTAS.CODIGO
FROM CT_PLANO_CONTAS 
LEFT JOIN CT_PLANO_REFERENCIAL ON CT_PLANO_REFERENCIAL.COD_CTA_REF = CT_PLANO_CONTAS.COD_CTA_REF
WHERE CT_PLANO_CONTAS.SINTETICO = 'N' 
AND REPLACE(CT_PLANO_CONTAS.COD_CTA_REF, '.', '') >= '3010107'
AND REPLACE(CT_PLANO_CONTAS.COD_CTA_REF, '.', '') < '3010110'
AND REPLACE(CT_PLANO_CONTAS.COD_CTA_REF, '.', '') NOT IN('30101070124', '30101070123') ---DEPRECIAÇÃO, AMORTIZAÇÃO
AND NOME not LIKE '%COMISSÃO%' and NOME not LIKE '%COMISSAO%' and NOME not LIKE '%FRETE S/ VENDA%' and NOME not LIKE '%FRETES S/ VENDA%'
AND (NOME LIKE '%COMERCIAL%' OR NOME LIKE '%VENDAS%'  )

---(-) OUTRAS DESPESAS OPERACIONAIS
INSERT INTO CT_DEMONSTRACAO_LINHA_CONTAS( RECNO_CT_DEMONSTRACAO_LINHA, CODIGO_CT_PLANO_CONTAS)
SELECT (SELECT R_E_C_N_O_ FROM CT_DEMONSTRACAO_LINHA WHERE DESCRICAO = '(-) OUTRAS DESPESAS OPERACIONAIS'),
CT_PLANO_CONTAS.CODIGO
FROM CT_PLANO_CONTAS
LEFT JOIN CT_PLANO_REFERENCIAL ON CT_PLANO_REFERENCIAL.COD_CTA_REF = CT_PLANO_CONTAS.COD_CTA_REF
WHERE REPLACE(CT_PLANO_CONTAS.COD_CTA_REF, '.', '') >= '30101090109'
AND REPLACE(CT_PLANO_CONTAS.COD_CTA_REF, '.', '') <= '30101090199'
AND NOME NOT LIKE '%COMERCIAL%'
AND CT_PLANO_CONTAS.SINTETICO = 'N'
UNION 
--OUTRAS PARTICIPAÇÕES DE LUCRO, DBENTURIES, ETC.
SELECT (SELECT R_E_C_N_O_ FROM CT_DEMONSTRACAO_LINHA WHERE DESCRICAO = '(-) OUTRAS DESPESAS OPERACIONAIS'),
CT_PLANO_CONTAS.CODIGO
FROM CT_PLANO_CONTAS
LEFT JOIN CT_PLANO_REFERENCIAL ON CT_PLANO_REFERENCIAL.COD_CTA_REF = CT_PLANO_CONTAS.COD_CTA_REF
WHERE REPLACE(CT_PLANO_CONTAS.COD_CTA_REF, '.', '') >= '30105' 
AND REPLACE(CT_PLANO_CONTAS.COD_CTA_REF, '.', '') < '30106'
AND NOME  NOT LIKE '%COMERCIAL%'
AND CT_PLANO_CONTAS.SINTETICO = 'N'
---OPERAÇÕES DESCONTINUADAS
UNION
SELECT (SELECT R_E_C_N_O_ FROM CT_DEMONSTRACAO_LINHA WHERE DESCRICAO = '(+) OUTRAS RECEITAS OPERACIONAIS'),
CT_PLANO_CONTAS.CODIGO
FROM CT_PLANO_CONTAS
LEFT JOIN CT_PLANO_REFERENCIAL ON CT_PLANO_REFERENCIAL.COD_CTA_REF = CT_PLANO_CONTAS.COD_CTA_REF
WHERE REPLACE(CT_PLANO_CONTAS.COD_CTA_REF, '.', '') IN('30101110104','30101110105','30101110106','30101110108')
AND CT_PLANO_CONTAS.SINTETICO = 'N'

---(+) OUTRAS RECEITAS OPERACIONAIS
INSERT INTO CT_DEMONSTRACAO_LINHA_CONTAS( RECNO_CT_DEMONSTRACAO_LINHA, CODIGO_CT_PLANO_CONTAS)
SELECT (SELECT R_E_C_N_O_ FROM CT_DEMONSTRACAO_LINHA WHERE DESCRICAO = '(+) OUTRAS RECEITAS OPERACIONAIS'),
CT_PLANO_CONTAS.CODIGO
FROM CT_PLANO_CONTAS
LEFT JOIN CT_PLANO_REFERENCIAL ON CT_PLANO_REFERENCIAL.COD_CTA_REF = CT_PLANO_CONTAS.COD_CTA_REF
WHERE REPLACE(CT_PLANO_CONTAS.COD_CTA_REF, '.', '') >= '30101050106'
AND REPLACE(CT_PLANO_CONTAS.COD_CTA_REF, '.', '') <= '30101050199'
AND CT_PLANO_CONTAS.SINTETICO = 'N'
UNION
---OPERAÇÕES DESCONTINUADAS
SELECT (SELECT R_E_C_N_O_ FROM CT_DEMONSTRACAO_LINHA WHERE DESCRICAO = '(+) OUTRAS RECEITAS OPERACIONAIS'),
CT_PLANO_CONTAS.CODIGO
FROM CT_PLANO_CONTAS
LEFT JOIN CT_PLANO_REFERENCIAL ON CT_PLANO_REFERENCIAL.COD_CTA_REF = CT_PLANO_CONTAS.COD_CTA_REF
WHERE REPLACE(CT_PLANO_CONTAS.COD_CTA_REF, '.', '') IN(
'30101110101',
'30101110102',
'30101110103',
'30101110107')
AND CT_PLANO_CONTAS.SINTETICO = 'N'


---(-) DEPRECIAÇÕES E AMORTIZAÇÕES
INSERT INTO CT_DEMONSTRACAO_LINHA_CONTAS( RECNO_CT_DEMONSTRACAO_LINHA, CODIGO_CT_PLANO_CONTAS)
SELECT (SELECT R_E_C_N_O_ FROM CT_DEMONSTRACAO_LINHA WHERE DESCRICAO = '(-) DEPRECIAÇÕES E AMORTIZAÇÕES'),
CT_PLANO_CONTAS.CODIGO
FROM CT_PLANO_CONTAS
LEFT JOIN CT_PLANO_REFERENCIAL ON CT_PLANO_REFERENCIAL.COD_CTA_REF = CT_PLANO_CONTAS.COD_CTA_REF
WHERE CT_PLANO_CONTAS.SINTETICO = 'N' AND REPLACE(CT_PLANO_CONTAS.COD_CTA_REF, '.', '') 
IN('30101070124', '30101070123') ---DEPRECIAÇÃO, AMORTIZAÇÃO


---(+) RECEITAS FINANCEIRAS
INSERT INTO CT_DEMONSTRACAO_LINHA_CONTAS( RECNO_CT_DEMONSTRACAO_LINHA, CODIGO_CT_PLANO_CONTAS)
SELECT (SELECT R_E_C_N_O_ FROM CT_DEMONSTRACAO_LINHA WHERE DESCRICAO = '(+) RECEITAS FINANCEIRAS'),
CT_PLANO_CONTAS.CODIGO
FROM CT_PLANO_CONTAS
LEFT JOIN CT_PLANO_REFERENCIAL ON CT_PLANO_REFERENCIAL.COD_CTA_REF = CT_PLANO_CONTAS.COD_CTA_REF
WHERE CT_PLANO_CONTAS.SINTETICO = 'N' 
AND REPLACE(CT_PLANO_CONTAS.COD_CTA_REF, '.', '') >= '30101050101'
AND REPLACE(CT_PLANO_CONTAS.COD_CTA_REF, '.', '') <= '30101050105'

---(-) DESPESAS FINANCEIRAS
INSERT INTO CT_DEMONSTRACAO_LINHA_CONTAS( RECNO_CT_DEMONSTRACAO_LINHA, CODIGO_CT_PLANO_CONTAS)
SELECT (SELECT R_E_C_N_O_ FROM CT_DEMONSTRACAO_LINHA WHERE DESCRICAO = '(-) DESPESAS FINANCEIRAS'),
CT_PLANO_CONTAS.CODIGO
FROM CT_PLANO_CONTAS
LEFT JOIN CT_PLANO_REFERENCIAL ON CT_PLANO_REFERENCIAL.COD_CTA_REF = CT_PLANO_CONTAS.COD_CTA_REF
WHERE REPLACE(CT_PLANO_CONTAS.COD_CTA_REF, '.', '') >= '30101090101'
AND REPLACE(CT_PLANO_CONTAS.COD_CTA_REF, '.', '') <= '30101090108'
AND CT_PLANO_CONTAS.SINTETICO = 'N' 


 
---(-) PROVISAO DE IMPOSTOS
INSERT INTO CT_DEMONSTRACAO_LINHA_CONTAS( RECNO_CT_DEMONSTRACAO_LINHA, CODIGO_CT_PLANO_CONTAS)
SELECT (SELECT R_E_C_N_O_ FROM CT_DEMONSTRACAO_LINHA WHERE DESCRICAO = '(-) PROVISÃO DE IMPOSTOS'),
CT_PLANO_CONTAS.CODIGO
FROM CT_PLANO_CONTAS
LEFT JOIN CT_PLANO_REFERENCIAL ON CT_PLANO_REFERENCIAL.COD_CTA_REF = CT_PLANO_CONTAS.COD_CTA_REF
WHERE REPLACE(CT_PLANO_CONTAS.COD_CTA_REF, '.', '') >= '302'
AND REPLACE(CT_PLANO_CONTAS.COD_CTA_REF, '.', '') < '303'
AND CT_PLANO_CONTAS.SINTETICO = 'N'

---VERIFICA SE ALGUMA CONTA FICOU REPETIDA E REMOVE
    DECLARE @CONT AS INT
	DECLARE @CONTA AS VARCHAR(20)
    
	DECLARE CUR CURSOR FAST_FORWARD FOR
	
	SELECT * FROM (
		SELECT COUNT(CODIGO_CT_PLANO_CONTAS) AS CONT, CODIGO_CT_PLANO_CONTAS FROM (
		SELECT CODIGO_CT_PLANO_CONTAS FROM CT_DEMONSTRACAO_LINHA_CONTAS
		INNER JOIN CT_DEMONSTRACAO_LINHA ON CT_DEMONSTRACAO_LINHA.R_E_C_N_O_ = CT_DEMONSTRACAO_LINHA_CONTAS.RECNO_CT_DEMONSTRACAO_LINHA
		INNER JOIN CT_DEMONSTRACAO ON CT_DEMONSTRACAO.R_E_C_N_O_ = CT_DEMONSTRACAO_LINHA.RECNO_CT_DEMONSTRACAO
		WHERE CT_DEMONSTRACAO.R_E_C_N_O_ = (SELECT TOP(1) R_E_C_N_O_ FROM CT_DEMONSTRACAO WHERE TIPO = 'DREBI' ORDER BY R_E_C_N_O_ DESC)
		) AS TBL GROUP BY CODIGO_CT_PLANO_CONTAS
	) AS TBL2 WHERE CONT > 1

	OPEN CUR
	FETCH NEXT FROM CUR INTO @CONT, @CONTA
	WHILE @@FETCH_STATUS = 0
	BEGIN
	  WHILE @CONT > 1
	  BEGIN
	  	  DELETE CT_DEMONSTRACAO_LINHA_CONTAS WHERE R_E_C_N_O_ IN(
			   SELECT TOP(1) CT_DEMONSTRACAO_LINHA_CONTAS.R_E_C_N_O_ 
			   FROM CT_DEMONSTRACAO_LINHA_CONTAS
			   INNER JOIN CT_DEMONSTRACAO_LINHA ON CT_DEMONSTRACAO_LINHA.R_E_C_N_O_ = CT_DEMONSTRACAO_LINHA_CONTAS.RECNO_CT_DEMONSTRACAO_LINHA
			   INNER JOIN CT_DEMONSTRACAO ON CT_DEMONSTRACAO.R_E_C_N_O_ = CT_DEMONSTRACAO_LINHA.RECNO_CT_DEMONSTRACAO
			   WHERE CT_DEMONSTRACAO.R_E_C_N_O_ = (SELECT TOP(1) R_E_C_N_O_ FROM CT_DEMONSTRACAO WHERE TIPO = 'DREBI' ORDER BY R_E_C_N_O_ DESC)
			   AND CT_DEMONSTRACAO_LINHA_CONTAS.CODIGO_CT_PLANO_CONTAS = @CONTA
			   ORDER BY CT_DEMONSTRACAO_LINHA_CONTAS.R_E_C_N_O_ DESC
			)

	    SET @CONT = @CONT - 1
	  END
	    
	  FETCH NEXT FROM CUR INTO @CONT, @CONTA
	END
	CLOSE CUR
	DEALLOCATE CUR

---verifica se tem alguma conta na analise de periodo que é de resultado e não ta presente na dre, SE TIVER INSERE PARA OUTRAS 
INSERT INTO CT_DEMONSTRACAO_LINHA_CONTAS( RECNO_CT_DEMONSTRACAO_LINHA, CODIGO_CT_PLANO_CONTAS)
SELECT (SELECT R_E_C_N_O_ FROM CT_DEMONSTRACAO_LINHA WHERE DESCRICAO = '(-) OUTRAS DESPESAS OPERACIONAIS'),
CT_PLANO_CONTAS.CODIGO 

FROM CT_PLANO_CONTAS WHERE CLASSIFICACAO > '3' AND SINTETICO = 'N' AND CODIGO NOT IN(
	SELECT CODIGO_CT_PLANO_CONTAS FROM CT_DEMONSTRACAO_LINHA_CONTAS
	INNER JOIN CT_DEMONSTRACAO_LINHA ON CT_DEMONSTRACAO_LINHA.R_E_C_N_O_ = CT_DEMONSTRACAO_LINHA_CONTAS.RECNO_CT_DEMONSTRACAO_LINHA
	INNER JOIN CT_DEMONSTRACAO ON CT_DEMONSTRACAO.R_E_C_N_O_ = CT_DEMONSTRACAO_LINHA.RECNO_CT_DEMONSTRACAO
	WHERE CT_DEMONSTRACAO.R_E_C_N_O_ = (SELECT TOP(1) R_E_C_N_O_ FROM CT_DEMONSTRACAO WHERE TIPO = 'DREBI' ORDER BY R_E_C_N_O_ DESC)
) AND CODIGO IN(

	SELECT COD_CONTA FROM CT_ANALISE_PERIODO_CONTABIL WHERE  RECNO_PERIODO_CONTABIL IN(SELECT R_E_C_N_O_ FROM CT_PERIODO_CONTABIL WHERE YEAR(DATA_INICIAL) >= 2020)
)








